package com.softwaresecured.burp.event.controller;

public enum BurpSeleniumScripterControllerEvent {
    TEST_CLICKED,
    RESET_CLICKED,
    SCRIPT_CONTENT_UPDATED,
    SCRIPT_ENABLED_TOGGLED,
    HEADLESS_TOGGLED,
    TIMEOUT_SET,
    SET_COLLAB_KEY_CLICKED,
    RESET_COLLAB_KEY_CLICKED,
    NEXT_INTERACTION_CLICKED,
    PREV_INTERACTION_CLICKED,
    TEST_REGEX_CLICKED,
    CLEAR_OUTPUT_CLICKED
}
