package com.softwaresecured.burp.constants;

public class BurpSeleniumScripterConstants {
    public static final String EXTENSION_NAME = "Burp Selenium Scripter";
    public static final String EXTENSION_INTERNAL_NAME = "BurpSeleniumScripter";
    public static final String[] defaultChromeDriverOptions = new String[]{
            "--dbus-stub",
            "--disable-single-click-autofill",
            "--disable-background-networking",
            "--disable-breakpad",
            "--disable-bundled-ppapi-flash",
            "--disable-client-side-phishing-detection",
            "--disable-component-update",
            "--disable-crash-reporter",
            "--disable-default-apps",
            "--disable-dev-shm-usage",
            "--disable-extensions",
            "--disable-features=NetworkService,NetworkServiceInProcess,NetworkTimeService,IdentityConsistency",
            "--disable-file-system",
            "--disable-gpu",
            "--disable-hang-monitor",
            "--disable-ipc-flooding-protection",
            "--disable-media-session-api",
            "--disable-new-zip-unpacker",
            "--disable-notifications",
            "--disable-permissions-api",
            "--disable-plugins-discovery",
            "--disable-popup-blocking",
            "--disable-prerender-local-predictor",
            "--disable-presentation-api",
            "--disable-prompt-on-repost",
            "--disable-settings-window",
            "--disable-speech-api",
            "--disable-sync",
            "--disable-xss-auditor",
            "--disk-cache-size=0",
            "--ignore-certificate-errors",
            "--media-cache-size=0",
            "--metrics-recording-only",
            "--no-default-browser-check",
            "--no-events",
            "--no-experiments",
            "--no-first-run",
            "--no-pings",
            "--no-sandbox",
            "--no-service-autorun",
            "--proxy-bypass-list=<-loopback>",
            "--safebrowsing-disable-auto-update",
            "--use-fake-device-for-media-stream",
            "--disable-signin-promo",
    };
}
