package com.softwaresecured.burp.event.model;

public enum BurpSeleniumScripterModelEvent {
    SCRIPT_SET,
    OUTPUT_SET,
    SCRIPT_THREAD_SET,
    SCRIPT_EXECUTION_STATE_CHANGED,
    SCRIPT_HEADLESS_SET,
    SCRIPT_ENABLED_SET,
    SCRIPT_TIMEOUT_SET,
    CHROME_DRIVER_VERSION_SET,
    CHROME_BROWSER_VERSION_SET,
    SCRIPT_LOADED,
    PROJECT_SETTINGS_LOADED
}
