package com.softwaresecured.burp.event.model;

public enum BurpSeleniumScripterModelEvent {
    SCRIPT_SET,
    OUTPUT_SET,
    SCRIPT_THREAD_SET,
    SCRIPT_EXECUTION_STATE_CHANGED,
    SCRIPT_HEADLESS_SET,
    SCRIPT_ENABLED_SET,
    SCRIPT_TIMEOUT_SET,
    CHROME_DRIVER_VERSION_SET,
    CHROME_BROWSER_VERSION_SET,
    SCRIPT_LOADED,
    INTERACTION_ADDED,
    INTERACTIONS_CLEARED,
    SELECTED_INTERACTION_INDEX_SET,
    COLLAB_DOMAIN_SET,
    COLLAB_SECRET_SET,
    LAST_INTERACTION_TIMESTAMP_UPDATED,
    HIGHLIGHT_ADDED,
    HIGHLIGHT_CLEARED,
    LAST_COLLAB_POLL_UPDATED, PROJECT_SETTINGS_LOADED
}
